# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"\x1a\n\x07Request\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2\xa8\x02\n\x0b\x45\x63hoService\x12.\n\x0etakeAllMetrics\x12\r.echo.Request\x1a\x0b.echo.Reply\"\x00\x12\x36\n\x16takeDefaultRangedValue\x12\r.echo.Request\x1a\x0b.echo.Reply\"\x00\x12\x33\n\x13\x63\x61llETLDataPipeline\x12\r.echo.Request\x1a\x0b.echo.Reply\"\x00\x12:\n\x1agetViolationsForSLAManager\x12\r.echo.Request\x1a\x0b.echo.Reply\"\x00\x12@\n getFutureViolationsForSLAManager\x12\r.echo.Request\x1a\x0b.echo.Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=20
  _REQUEST._serialized_end=46
  _REPLY._serialized_start=48
  _REPLY._serialized_end=72
  _ECHOSERVICE._serialized_start=75
  _ECHOSERVICE._serialized_end=371
# @@protoc_insertion_point(module_scope)
