# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import echo_pb2 as echo__pb2


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.takeAllMetrics = channel.unary_unary(
                '/echo.EchoService/takeAllMetrics',
                request_serializer=echo__pb2.Request.SerializeToString,
                response_deserializer=echo__pb2.Reply.FromString,
                )
        self.takeMetadata = channel.unary_unary(
                '/echo.EchoService/takeMetadata',
                request_serializer=echo__pb2.Request.SerializeToString,
                response_deserializer=echo__pb2.Reply.FromString,
                )
        self.takeValues = channel.unary_unary(
                '/echo.EchoService/takeValues',
                request_serializer=echo__pb2.Request.SerializeToString,
                response_deserializer=echo__pb2.Reply.FromString,
                )
        self.takePred = channel.unary_unary(
                '/echo.EchoService/takePred',
                request_serializer=echo__pb2.Request.SerializeToString,
                response_deserializer=echo__pb2.Reply.FromString,
                )


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def takeAllMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def takeMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def takeValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def takePred(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'takeAllMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.takeAllMetrics,
                    request_deserializer=echo__pb2.Request.FromString,
                    response_serializer=echo__pb2.Reply.SerializeToString,
            ),
            'takeMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.takeMetadata,
                    request_deserializer=echo__pb2.Request.FromString,
                    response_serializer=echo__pb2.Reply.SerializeToString,
            ),
            'takeValues': grpc.unary_unary_rpc_method_handler(
                    servicer.takeValues,
                    request_deserializer=echo__pb2.Request.FromString,
                    response_serializer=echo__pb2.Reply.SerializeToString,
            ),
            'takePred': grpc.unary_unary_rpc_method_handler(
                    servicer.takePred,
                    request_deserializer=echo__pb2.Request.FromString,
                    response_serializer=echo__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def takeAllMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/takeAllMetrics',
            echo__pb2.Request.SerializeToString,
            echo__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def takeMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/takeMetadata',
            echo__pb2.Request.SerializeToString,
            echo__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def takeValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/takeValues',
            echo__pb2.Request.SerializeToString,
            echo__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def takePred(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.EchoService/takePred',
            echo__pb2.Request.SerializeToString,
            echo__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
